### ISSUE TITLE
Correct ISO dates in sample data file (and discussion)

### ISSUE THREAD

**Issue by timgdavies** [open-contracting/sample-data#8]
The 'fictional example' sample data files currently only includes dates, not date time (i.e. `2015-01-12` nor `2015-01-12T00:00:00+00:00'`).

The standard specifies we should always have date-time, not just date.  However, the validator doesn't pick up failure to use data-time right now. 

Date-time with timezone is important for cross-country analysis, and particularly important on things like closing dates for tenders etc.

We should:
- Update the dates in 'fictional example' - this will need careful thought to know whether dates should be set as a particular time of day, midnight at the start of the day, or midnight at the end of the day;
- Check whether we need extra documentation and guidance on date-time;
- Check what changes are needed to schema validator, and to validation support tools, to check dates are being handled right;

**Comment by Bjwebb** [comment]
There's an issue for this in Cove (the software that will soon replace the current validator) at https://github.com/OpenDataServices/cove/issues/194 . This is now fixed in the dev copy of Cove http://dev.cove.opendataservices.coop/ocds/?source_url=https://raw.githubusercontent.com/open-contracting/sample-data/master/fictional-example/ocds-213czf-000-00001-01-planning.json

**Comment by timgdavies** [comment]
Dates are fixed in examples now (issue #14). 

Other validation issues remain to action if decision that this should be done.

**Comment by Bjwebb** [comment]
There's an issue for validating dates in the automated tests https://github.com/open-contracting/sample-data/issues/16

Can this issue now be closed?

**Comment by jpmckinney** [comment]
@Bjwebb Seems like yes.
