### ISSUE TITLE
Missing individual release examples

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/sample-data#88]
The individual release examples in the [fictional-example/1.1 folder](https://github.com/open-contracting/sample-data/tree/master/fictional-example/1.1) seem to have been removed.

@jpmckinney it looks like 92c875e66ed06fbf73de453365fe294615520930 was the commit that removed them, here's the folder before the commit: https://github.com/open-contracting/sample-data/tree/3085c151e910801884ffb75df9250df1679030c4/fictional-example/1.1

Was that intentional?

**Comment by jpmckinney** [comment]
I had to regenerate the files – however, based on the available instructions (moved here: https://github.com/open-contracting/sample-data/tree/master/fictional-example#11), what you ended up with was a single package - not six packages as was previously available.

If instructions can be provided, we can restore the individual packages. It also wasn't clear why we needed six packages with one release each, instead of one package with six releases (present state).

**Comment by duncandewhurst** [comment]
> However, it's not clear why we need six packages with one release each, instead of one package with six releases (present state).

I don't know the original reasoning behind having individual packages, but assuming that sometimes these examples are likely to be read by eye, it's easier for a user seeking to answer "what does an award release look like?" to find an award release in the separate packages, rather than trying to find an award release in the combined package.

Separately, I just noticed that the change has broken the [try loading some sample data link](http://standard.open-contracting.org/review/?source_url=https://raw.githubusercontent.com/open-contracting/sample-data/master/fictional-example/1.1/ocds-213czf-000-00001-02-tender.json) in the data review tool.

Could we add `ocdskit split-release-packages 1` to the instructions?

**Comment by jpmckinney** [comment]
Done – added the files and instructions.
